# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbstorage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedfile',
            name='trusted',
            field=models.BooleanField(default=False, help_text='Is this file trusted to be served from our own domain?'),
        ),
    ]
